---
- name: Test Vault Secret Access for sam
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Print the value for sam from Vault
      ansible.builtin.debug:
        msg: "{{ lookup('community.hashi_vault', 'secret=kv/data/ansible token=hvs.B9BpUmHDLk4bDVIiS2esdbYK url=http://vault.awx.svc.cluster.local:8200 engine_mount_point=kv').sam }}"
